from __future__ import annotations

import re
import subprocess
from collections import Counter, defaultdict
from collections.abc import Sequence
from pathlib import Path
from typing import TypedDict

from rebrief.core.ignore import IgnoreMatcher
from rebrief.plugins.builtin._helpers import is_test_or_fixture_path

MAX_BLAME_FILES = 250
MAX_FILE_BYTES = 1024 * 1024
RECENT_ACTIVITY_SINCE = "90 days ago"
RAPID_SESSION_WINDOW_SECONDS = 30 * 60
RAPID_SESSION_MIN_COMMITS = 3
AI_ASSISTED_THRESHOLD = 25.0
LOW_ACTIVITY_LINE_THRESHOLD = 20

MONOREPO_BUCKETS: frozenset[str] = frozenset(
    {"apps", "packages", "services", "libs", "src"}
)

SOURCE_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".py",
        ".js",
        ".jsx",
        ".ts",
        ".tsx",
        ".mjs",
        ".cjs",
        ".go",
        ".rs",
        ".java",
        ".kt",
        ".kts",
        ".scala",
        ".php",
        ".rb",
        ".c",
        ".cc",
        ".cpp",
        ".h",
        ".hpp",
        ".cs",
        ".swift",
        ".vue",
        ".svelte",
        ".sql",
        ".sh",
        ".bash",
        ".zsh",
        ".ps1",
        ".r",
        ".lua",
        ".ex",
        ".exs",
        ".erl",
        ".hrl",
        ".clj",
        ".cljs",
        ".hs",
        ".ml",
        ".mli",
        ".dart",
        ".zig",
    }
)

GENERATED_SUFFIXES: tuple[str, ...] = (
    ".min.js",
    ".min.css",
    "_pb2.py",
    ".pb.go",
    ".generated.ts",
    ".generated.js",
)

GENERATED_FILENAMES: frozenset[str] = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "Cargo.lock",
        "poetry.lock",
        "composer.lock",
        "Gemfile.lock",
        "go.sum",
    }
)

DOC_DIR_SEGMENTS: frozenset[str] = frozenset({"docs", "documentation", "doc"})

AI_TOOL_PATTERNS: tuple[tuple[str, str], ...] = (
    ("claude", "Claude"),
    ("cursor", "Cursor"),
    ("copilot", "Copilot"),
    ("ibm bob", "IBM Bob"),
    ("devin", "Devin"),
    ("gemini", "Gemini"),
    ("chatgpt", "ChatGPT"),
    ("codex", "Codex"),
    ("windsurf", "Windsurf"),
    ("cody", "Cody"),
)

CO_AUTHOR_RE = re.compile(
    r"^Co-authored-by:\s*(.+?)\s*<",
    re.IGNORECASE | re.MULTILINE,
)
AI_WORD_RE = re.compile(
    r"\b("
    r"claude|cursor|copilot|ibm\s+bob|devin|gemini|chatgpt|codex|windsurf|cody"
    r")\b",
    re.IGNORECASE,
)
INLINE_SIGNATURE_RE = re.compile(
    r"(Co-authored-by:\s*(?:Claude|Cursor|Copilot|GitHub Copilot|IBM Bob|Devin|Gemini|ChatGPT|Codex|Windsurf|Cody)"
    r"|Generated by (?:GitHub )?Copilot"
    r"|AI-generated)",
    re.IGNORECASE,
)
BLAME_HEADER_RE = re.compile(r"^[0-9a-f]{40} ")


class ModuleOwnership(TypedDict):
    contributors: dict[str, float]
    primary_owner: str
    primary_percent: float
    secondary: str
    secondary_percent: float
    ai_assisted: bool
    ai_percent: float
    ai_tools: list[str]
    expertise_level: str
    rapid_ai_session: bool
    line_count: int


class OwnershipResult(TypedDict):
    modules: dict[str, ModuleOwnership]
    skipped: bool
    skip_reason: str | None


def _empty_result(*, skipped: bool = False, skip_reason: str | None = None) -> OwnershipResult:
    return {
        "modules": {},
        "skipped": skipped,
        "skip_reason": skip_reason,
    }


def module_key_for_path(relative_path: str) -> str:
    """Return a module path key such as ``apps/backend/`` or ``.``."""
    normalized = relative_path.replace("\\", "/")
    parts = [part for part in normalized.split("/") if part]
    if not parts:
        return "."
    if len(parts) == 1:
        return "."
    if parts[0] in MONOREPO_BUCKETS and len(parts) >= 3:
        return f"{parts[0]}/{parts[1]}/"
    return f"{parts[0]}/"


def detect_ai_tools_in_text(text: str) -> list[str]:
    """Extract canonical AI tool names from commit messages or co-author lines."""
    found: set[str] = set()
    lowered = text.lower()

    for match in CO_AUTHOR_RE.finditer(text):
        name = match.group(1).strip()
        for pattern, label in AI_TOOL_PATTERNS:
            if pattern in name.lower():
                found.add(label)

    for pattern, label in AI_TOOL_PATTERNS:
        if re.search(rf"\b{re.escape(pattern)}\b", lowered):
            found.add(label)

    return sorted(found)


def is_ai_author(author_name: str, author_email: str) -> list[str]:
    """Return AI tool labels inferred from blame author metadata."""
    combined = f"{author_name} {author_email}".lower()
    found: list[str] = []
    markers = (
        ("claude", "Claude"),
        ("anthropic", "Claude"),
        ("cursor", "Cursor"),
        ("cursoragent", "Cursor"),
        ("copilot", "Copilot"),
        ("github-copilot", "Copilot"),
        ("ibm bob", "IBM Bob"),
        ("devin", "Devin"),
        ("gemini", "Gemini"),
        ("chatgpt", "ChatGPT"),
        ("openai", "ChatGPT"),
        ("codex", "Codex"),
        ("windsurf", "Windsurf"),
        ("cody", "Cody"),
    )
    for needle, label in markers:
        if needle in combined and label not in found:
            found.append(label)
    return found


def classify_expertise(
    *,
    primary_percent: float,
    line_count: int,
    recent_churn: int,
) -> str:
    if line_count < LOW_ACTIVITY_LINE_THRESHOLD and recent_churn == 0:
        return "Low Activity"
    if recent_churn >= 3:
        return "High Activity"
    if primary_percent >= 70 and recent_churn <= 1:
        return "Stable / Maintenance"
    if primary_percent < 50:
        return "Shared"
    if recent_churn == 0:
        return "Low Activity"
    return "Stable / Maintenance"


def format_secondary_display(
    *,
    secondary: str,
    secondary_percent: float,
    ai_assisted: bool,
    ai_percent: float,
    ai_tools: list[str],
) -> str:
    if ai_assisted and ai_percent >= AI_ASSISTED_THRESHOLD:
        tools = "/".join(ai_tools) if ai_tools else "AI"
        return f"🤖 AI-Assisted ({ai_percent:.0f}% {tools})"
    if secondary:
        return f"{secondary} ({secondary_percent:.0f}%)"
    return "—"


def format_ownership_table(modules: dict[str, ModuleOwnership]) -> list[str]:
    """Render markdown table rows for ownership modules."""
    if not modules:
        return ["- None detected."]

    lines = [
        "| Module / Path | Primary Owner | Secondary / AI Contributor | Expertise Level |",
        "|---|---|---|---|",
    ]
    for module_path in sorted(modules):
        entry = modules[module_path]
        secondary = format_secondary_display(
            secondary=entry["secondary"],
            secondary_percent=entry["secondary_percent"],
            ai_assisted=entry["ai_assisted"],
            ai_percent=entry["ai_percent"],
            ai_tools=entry["ai_tools"],
        )
        lines.append(
            f"| `{module_path}` | {entry['primary_owner']} "
            f"({entry['primary_percent']:.0f}%) | {secondary} | "
            f"{entry['expertise_level']} |"
        )
    return lines


def _round_percentages(counts: dict[str, int]) -> dict[str, float]:
    total = sum(counts.values())
    if total <= 0:
        return {}

    raw = {name: (count / total) * 100 for name, count in counts.items()}
    rounded = {name: float(int(value + 0.5)) for name, value in raw.items()}
    diff = 100 - sum(rounded.values())
    if diff != 0:
        largest = max(counts, key=lambda key: counts[key])
        rounded[largest] = max(0.0, rounded[largest] + diff)
    return rounded


class OwnershipParser:
    def __init__(
        self,
        repo_path: str,
        *,
        paths: list[str] | None = None,
        skip: bool = False,
        git_root: str | Path | None = None,
        path_prefix: str | None = None,
        extra_ignore_patterns: Sequence[str] = (),
    ) -> None:
        self._repo_path = Path(repo_path)
        self._git_root = Path(git_root) if git_root is not None else self._repo_path
        self._path_prefix = path_prefix
        self._paths = paths
        self._skip = skip
        self._ignore_matcher = IgnoreMatcher(
            repo_path, extra_patterns=extra_ignore_patterns
        )

    def parse(self) -> OwnershipResult:
        if self._skip:
            return _empty_result(skipped=True, skip_reason="disabled via --no-blame")

        if not (self._git_root / ".git").exists():
            return _empty_result()

        try:
            blame_files = self._collect_blame_files()
            if not blame_files:
                return _empty_result()

            module_lines: dict[str, Counter[str]] = defaultdict(Counter)
            module_ai_lines: dict[str, int] = defaultdict(int)
            module_commits: dict[str, set[str]] = defaultdict(set)
            all_shas: set[str] = set()
            inline_ai_files: set[str] = set()
            file_blame: dict[str, list[tuple[str, str]]] = {}

            for relative in blame_files:
                module = module_key_for_path(relative)
                if self._file_has_inline_ai_signature(relative):
                    inline_ai_files.add(relative)
                blame_data = self._blame_file(relative)
                file_blame[relative] = blame_data
                for author, sha in blame_data:
                    module_lines[module][author] += 1
                    module_commits[module].add(sha)
                    all_shas.add(sha)

            commit_meta = self._fetch_commit_meta_batch(all_shas)
            ai_commits: set[str] = set()
            for sha, meta in commit_meta.items():
                if (
                    detect_ai_tools_in_text(meta.get("message", ""))
                    or is_ai_author(meta.get("author", ""), meta.get("email", ""))
                ):
                    ai_commits.add(sha)

            for relative, blame_data in file_blame.items():
                module = module_key_for_path(relative)
                inline_ai = relative in inline_ai_files
                for _author, sha in blame_data:
                    if sha in ai_commits or inline_ai:
                        module_ai_lines[module] += 1

            recent_churn = self._recent_module_churn(blame_files)
            modules = self._build_modules(
                module_lines,
                module_ai_lines,
                module_commits,
                commit_meta,
                ai_commits,
                recent_churn,
            )
            return {
                "modules": modules,
                "skipped": False,
                "skip_reason": None,
            }
        except (FileNotFoundError, subprocess.CalledProcessError):
            return _empty_result()

    def _run_git(self, args: list[str]) -> str:
        result = subprocess.run(
            ["git", *args],
            cwd=self._git_root,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout

    def _matches_prefix(self, path: str) -> bool:
        if self._path_prefix is None:
            return True
        normalized = path.replace("\\", "/")
        prefix = self._path_prefix
        if prefix.endswith("/"):
            return normalized.startswith(prefix) or normalized == prefix.rstrip("/")
        return normalized.startswith(f"{prefix}/") or normalized == prefix

    def _collect_blame_files(self) -> list[str]:
        if self._paths is not None:
            candidates = [path.replace("\\", "/") for path in self._paths]
        else:
            output = self._run_git(["ls-files"])
            candidates = [
                line.strip().replace("\\", "/")
                for line in output.splitlines()
                if line.strip()
            ]

        eligible: list[tuple[int, str]] = []
        for relative in candidates:
            if not self._matches_prefix(relative):
                continue
            if not self._is_eligible_source(relative):
                continue
            file_path = self._git_root / relative
            if not file_path.is_file():
                continue
            try:
                size = file_path.stat().st_size
            except OSError:
                continue
            eligible.append((size, relative))

        eligible.sort(key=lambda item: (-item[0], item[1]))
        return [relative for _, relative in eligible[:MAX_BLAME_FILES]]

    def _is_eligible_source(self, relative: str) -> bool:
        normalized = relative.replace("\\", "/")
        lower = normalized.lower()

        if is_test_or_fixture_path(normalized):
            return False
        if self._ignore_matcher.is_ignored(normalized, is_dir=False):
            return False

        parts = [part.lower() for part in normalized.split("/") if part]
        if any(part in DOC_DIR_SEGMENTS for part in parts):
            return False

        name = Path(normalized).name
        if name in GENERATED_FILENAMES:
            return False
        if name.endswith(".md"):
            return False
        if any(lower.endswith(suffix) for suffix in GENERATED_SUFFIXES):
            return False
        if name.endswith(".lock"):
            return False

        suffix = Path(normalized).suffix.lower()
        if suffix not in SOURCE_EXTENSIONS:
            return False

        return True

    def _file_has_inline_ai_signature(self, relative: str) -> bool:
        file_path = self._git_root / relative
        try:
            data = file_path.read_bytes()
        except OSError:
            return False
        if len(data) > MAX_FILE_BYTES:
            return False
        if b"\x00" in data[:8192]:
            return False
        try:
            text = data.decode("utf-8", errors="ignore")
        except Exception:
            return False
        head = text[:2000]
        tail = text[-2000:] if len(text) > 2000 else ""
        return bool(INLINE_SIGNATURE_RE.search(head) or INLINE_SIGNATURE_RE.search(tail))

    def _blame_file(self, relative: str) -> list[tuple[str, str]]:
        output = self._run_git(["blame", "--line-porcelain", "-w", "--", relative])
        results: list[tuple[str, str]] = []
        author: str | None = None
        sha: str | None = None

        for line in output.splitlines():
            if line.startswith("\t"):
                if author and sha:
                    results.append((author, sha))
                continue
            if line.startswith("author "):
                author = line[7:]
            elif BLAME_HEADER_RE.match(line):
                sha = line[:40]

        return results

    def _fetch_commit_meta_batch(self, shas: set[str]) -> dict[str, dict[str, str]]:
        if not shas:
            return {}

        meta: dict[str, dict[str, str]] = {}
        sha_list = sorted(shas)
        chunk_size = 100
        for start in range(0, len(sha_list), chunk_size):
            chunk = sha_list[start : start + chunk_size]
            try:
                output = self._run_git(
                    [
                        "log",
                        "--format=%H<<>>%an<<>>%ae<<>>%ct<<>>%B<<>>END",
                        "--no-walk",
                        *chunk,
                    ]
                )
            except subprocess.CalledProcessError:
                continue

            for block in output.split("<<>>END"):
                block = block.strip()
                if not block or "<<>>" not in block:
                    continue
                parts = block.split("<<>>", 4)
                if len(parts) < 5:
                    continue
                sha, author, email, timestamp, message = parts
                meta[sha] = {
                    "author": author,
                    "email": email,
                    "timestamp": timestamp,
                    "message": message.strip(),
                }
        return meta

    def _recent_module_churn(self, blame_files: list[str]) -> dict[str, int]:
        if not blame_files:
            return {}

        counts: Counter[str] = Counter()
        try:
            output = self._run_git(
                [
                    "log",
                    f"--since={RECENT_ACTIVITY_SINCE}",
                    "--name-only",
                    "--pretty=format:",
                    "--",
                    *blame_files,
                ]
            )
        except subprocess.CalledProcessError:
            return {}

        for line in output.splitlines():
            stripped = line.strip().replace("\\", "/")
            if not stripped:
                continue
            module = module_key_for_path(stripped)
            counts[module] += 1
        return dict(counts)

    def _build_modules(
        self,
        module_lines: dict[str, Counter[str]],
        module_ai_lines: dict[str, int],
        module_commits: dict[str, set[str]],
        commit_meta: dict[str, dict[str, str]],
        ai_commits: set[str],
        recent_churn: dict[str, int],
    ) -> dict[str, ModuleOwnership]:
        modules: dict[str, ModuleOwnership] = {}

        for module, author_counts in sorted(module_lines.items()):
            total_lines = sum(author_counts.values())
            if total_lines <= 0:
                continue

            percentages = _round_percentages(dict(author_counts))
            ranked = sorted(
                percentages.items(),
                key=lambda item: (-item[1], item[0]),
            )

            ai_line_count = module_ai_lines.get(module, 0)
            ai_percent = round((ai_line_count / total_lines) * 100, 1)

            ai_tools: set[str] = set()
            for sha in module_commits.get(module, set()):
                meta = commit_meta.get(sha, {})
                ai_tools.update(detect_ai_tools_in_text(meta.get("message", "")))
                ai_tools.update(
                    is_ai_author(meta.get("author", ""), meta.get("email", ""))
                )

            rapid_ai_session = self._detect_rapid_ai_session(
                module_commits.get(module, set()),
                ai_commits,
                commit_meta,
            )

            human_ranked = [
                (name, pct)
                for name, pct in ranked
                if not is_ai_author(name, "")
            ]
            if human_ranked:
                primary_owner, primary_percent = human_ranked[0]
                secondary_candidates = human_ranked[1:]
            else:
                primary_owner, primary_percent = ranked[0]
                secondary_candidates = ranked[1:]

            secondary = ""
            secondary_percent = 0.0
            if secondary_candidates:
                secondary, secondary_percent = secondary_candidates[0]
            elif ai_percent >= AI_ASSISTED_THRESHOLD:
                secondary = "AI"
                secondary_percent = ai_percent

            ai_assisted = ai_percent >= AI_ASSISTED_THRESHOLD or bool(ai_tools)

            expertise = classify_expertise(
                primary_percent=primary_percent,
                line_count=total_lines,
                recent_churn=recent_churn.get(module, 0),
            )

            modules[module] = {
                "contributors": percentages,
                "primary_owner": primary_owner,
                "primary_percent": primary_percent,
                "secondary": secondary,
                "secondary_percent": secondary_percent,
                "ai_assisted": ai_assisted,
                "ai_percent": ai_percent,
                "ai_tools": sorted(ai_tools),
                "expertise_level": expertise,
                "rapid_ai_session": rapid_ai_session,
                "line_count": total_lines,
            }

        return modules

    def _detect_rapid_ai_session(
        self,
        shas: set[str],
        ai_commits: set[str],
        commit_meta: dict[str, dict[str, str]],
    ) -> bool:
        module_ai_shas = [sha for sha in shas if sha in ai_commits]
        if len(module_ai_shas) < RAPID_SESSION_MIN_COMMITS:
            return False

        timestamps: list[int] = []
        for sha in module_ai_shas:
            raw = commit_meta.get(sha, {}).get("timestamp", "")
            try:
                timestamps.append(int(raw))
            except ValueError:
                continue

        if len(timestamps) < RAPID_SESSION_MIN_COMMITS:
            return False

        timestamps.sort()
        for index in range(len(timestamps) - RAPID_SESSION_MIN_COMMITS + 1):
            window = timestamps[index : index + RAPID_SESSION_MIN_COMMITS]
            if window[-1] - window[0] <= RAPID_SESSION_WINDOW_SECONDS:
                return True
        return False
