from __future__ import annotations

import argparse
import sys
from pathlib import Path

COMMENT_MARKER = "<!-- rebrief-ci-report -->"
GITHUB_COMMENT_LIMIT = 65_536
RESERVED_CHARS = 1_000

SECTION_OVERVIEW = "## 1. Project Overview (Executive Summary)"
SECTION_STACK = "## 2. Technology Stack and Dependencies"
SECTION_TIMELINE = "## 3. Solution Timeline (Git History)"
SECTION_RISKS = "## 4. Risk Map (AI Debt & Security)"
SECTION_DOC_DRIFT = "## 6. 📉 Documentation Freshness & Drift"
SECTION_CHECKLIST = '## 7. Developer Checklist ("Where to Start")'

CRITICAL_HEADING = "### [CRITICAL]"
WARNING_HEADING = "### [WARNING]"
NONE_DETECTED = "- None detected."


def _split_sections(report: str) -> dict[str, str]:
    """Split REBRIEF.md into named sections by level-2 headings."""
    sections: dict[str, str] = {}
    current_key: str | None = None
    current_lines: list[str] = []

    for line in report.splitlines():
        if line.startswith("## "):
            if current_key is not None:
                sections[current_key] = "\n".join(current_lines).strip()
            current_key = line
            current_lines = [line]
        elif current_key is not None:
            current_lines.append(line)

    if current_key is not None:
        sections[current_key] = "\n".join(current_lines).strip()

    return sections


def _extract_subsection(section_text: str, heading: str) -> list[str]:
    """Return lines belonging to a level-3 subsection until the next heading."""
    lines = section_text.splitlines()
    collecting = False
    result: list[str] = []

    for line in lines:
        if line == heading:
            collecting = True
            continue
        if collecting and line.startswith("### "):
            break
        if collecting:
            result.append(line)

    return result


def section_has_findings(lines: list[str]) -> bool:
    """True when a risk subsection contains bullets other than '- None detected.'."""
    return any(
        line.startswith("- ") and line.strip() != NONE_DETECTED for line in lines
    )


def has_warning_or_critical_risks(report: str) -> bool:
    """Return True if CRITICAL or WARNING subsections have findings."""
    sections = _split_sections(report)
    risks_section = sections.get(SECTION_RISKS, "")
    if not risks_section:
        return False

    critical = _extract_subsection(risks_section, CRITICAL_HEADING)
    warning = _extract_subsection(risks_section, WARNING_HEADING)
    return section_has_findings(critical) or section_has_findings(warning)


def _build_collapsible(stack: str, timeline: str) -> str:
    if not stack and not timeline:
        return ""

    body_parts = [part for part in (stack, timeline) if part]
    body = "\n\n".join(body_parts)
    return (
        "<details>\n"
        "<summary>Technology Stack & Git Timeline</summary>\n\n"
        f"{body}\n"
        "</details>"
    )


def _truncate_body(body: str, max_length: int) -> tuple[str, bool]:
    if len(body) <= max_length:
        return body, False

    notice = (
        "\n\n> Report truncated (exceeded GitHub comment limit). "
        "Download the full `REBRIEF.md` from workflow artifacts.\n"
    )
    available = max_length - len(notice)
    if available <= 0:
        return notice.strip(), True

    return body[:available].rstrip() + notice, True


def build_pr_comment(
    report: str,
    *,
    commit_sha: str = "",
    run_url: str = "",
    timestamp: str = "",
    max_length: int = GITHUB_COMMENT_LIMIT - RESERVED_CHARS,
) -> tuple[str, bool]:
    """
    Build a PR comment body from a full REBRIEF.md report.

    Returns (comment_body, was_truncated).
    """
    sections = _split_sections(report)

    overview = sections.get(SECTION_OVERVIEW, "")
    stack = sections.get(SECTION_STACK, "")
    timeline = sections.get(SECTION_TIMELINE, "")
    risks = sections.get(SECTION_RISKS, "")
    doc_drift = sections.get(SECTION_DOC_DRIFT, "")
    checklist = sections.get(SECTION_CHECKLIST, "")

    meta_parts: list[str] = []
    if commit_sha:
        meta_parts.append(f"Commit `{commit_sha[:7]}`")
    if timestamp:
        meta_parts.append(timestamp)
    if run_url:
        meta_parts.append(f"[workflow run]({run_url})")

    meta_line = " · ".join(meta_parts)

    parts = [
        COMMENT_MARKER,
        "## rebrief scan report",
    ]
    if meta_line:
        parts.append(f"\n<sub>{meta_line}</sub>\n")

    primary = "\n\n".join(
        part for part in (overview, risks, doc_drift, checklist) if part
    )
    parts.append(primary)

    collapsible = _build_collapsible(stack, timeline)
    if collapsible:
        parts.append(collapsible)

    parts.append(
        "\n---\n"
        "<sub>Generated by "
        '<a href="https://pypi.org/project/rebrief/">rebrief</a>'
        "</sub>"
    )

    body = "\n\n".join(parts)
    return _truncate_body(body, max_length)


def _read_report(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Report not found: {path}")
    return path.read_text(encoding="utf-8")


def _cmd_build(args: argparse.Namespace) -> int:
    report = _read_report(Path(args.report_path))
    comment, truncated = build_pr_comment(
        report,
        commit_sha=args.commit_sha or "",
        run_url=args.run_url or "",
        timestamp=args.timestamp or "",
    )
    output_path = Path(args.output)
    output_path.write_text(comment, encoding="utf-8")

    if truncated:
        print("::warning::PR comment was truncated to fit GitHub's character limit.")
        if args.truncated_flag:
            flag_path = Path(args.truncated_flag)
            flag_path.write_text("true", encoding="utf-8")

    return 0


def _cmd_has_risks(args: argparse.Namespace) -> int:
    report = _read_report(Path(args.report_path))
    has_risks = has_warning_or_critical_risks(report)

    if args.output:
        Path(args.output).write_text("true" if has_risks else "false", encoding="utf-8")

    # Exit 0 when risks found (continue workflow), 2 when none (skip comment)
    return 0 if has_risks else 2


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build PR comments from REBRIEF.md")
    subparsers = parser.add_subparsers(dest="command", required=True)

    build_parser = subparsers.add_parser("build", help="Build PR comment body")
    build_parser.add_argument("--report-path", required=True)
    build_parser.add_argument("--output", required=True)
    build_parser.add_argument("--commit-sha", default="")
    build_parser.add_argument("--run-url", default="")
    build_parser.add_argument("--timestamp", default="")
    build_parser.add_argument(
        "--truncated-flag",
        default="",
        help="Write 'true' to this file when comment was truncated",
    )
    build_parser.set_defaults(func=_cmd_build)

    risks_parser = subparsers.add_parser(
        "has-risks",
        help="Check for WARNING/CRITICAL findings (exit 2 if none)",
    )
    risks_parser.add_argument("--report-path", required=True)
    risks_parser.add_argument(
        "--output",
        default="",
        help="Write 'true' or 'false' to this file",
    )
    risks_parser.set_defaults(func=_cmd_has_risks)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
